add export to lean (#200)

diff --git a/config b/config
--- a/config
+++ b/config
@@ -14,14 +14,13 @@ fi
 
 usage() {
     cat <<__EOF__
-usage: `basename $0` \$hollight_file.ml \$root_path [rocq_file_or_module] ... [\$mapping.mk] [\$mapping.lp]
+usage: `basename $0` \$hollight_file.ml \$root_path [--mapping \$mapping.lp] [--renaming \$renaming.lp] [rocq_or_lean_file_or_module] ... [\$deps.mk]
 
 arguments:
   \$hollight_file.ml: path to an ml file relative to \$HOLLIGHT_DIR
   \$root_path: name of the generated library
-  rocq_file_or_module: rocq module that needs to be imported in generated files
-  \$mapping.mk: dependencies of vo files given in arguments
-  \$mapping.lp: mappings between lambdapi and rocq
+  file_or_module: modules that need to be imported in generated files
+  \$deps.mk: dependencies of Rocq files given in arguments
 
 effect in the current directory:
 - create a file CONFIG containing the command used to create links
@@ -30,31 +29,40 @@ effect in the current directory:
 - create a file lambdapi.pkg
 - create a file _CoqProject
 - create a file MAPPING containing \$mapping.lp
+- create a file RENAMING containing \$renaming.lp
 - create a file REQUIRING containing the list of Rocq module names that need to be imported (in the same order as they are given in the command)
-- create a file VOFILES containing the list of Rocq module names corresponding to the Rocq files given in arguments with file extension ".vo"
-- add links to \$file.mk, the Rocq files given in argument and other files in \$HOL2DK_DIR and \$HOLLIGHT_DIR for translating and checking the proofs of \$hollight_file.ml
+- create a file ROCQFILES containing the list of Rocq files given in argument
+- create a file LEANFILES containing the list of Lean files given in argument
+- copy \$deps.mk and the Rocq files given in argument
+- copy theory_hol.dk and theory_hol.lp from \$HOL2DK_DIR
+- add links to Makefile, BIG_FILES, part.mk and spec.mk from \$HOL2DK_DIR
+- add links to \$hollight_file.prf, \$hollight_file.nbp, \$hollight_file.sig, \$hollight_file.thm, \$hollight_file.pos, and \$hollight_file.use files in \$HOLLIGHT_DIR
 __EOF__
 }
 
-error() {
-    echo error: $1
-    echo
-    usage
-    exit 1
-}
+error() { echo error: $1; echo; usage; exit 1; }
+
+invalid_arg() { error invalid argument \"$1\"; }
+
+if test $# -eq 0; then usage; exit 0; fi
 
 parse_args() {
     if test $# -ne 0; then
         case $1 in
-            *.lp)
-                if test -z "$mapping"
-                then
-                    mapping=$1
-                    shift
-                    parse_args $*
-                else
-                    error 'too many lp files'
-                fi;;
+            --mapping)
+                if test -n "$mapping"; then error 'mapping file already set'; fi
+                shift
+                if test $# -eq 0; then error 'mapping file missing'; fi
+                mapping=$1
+                shift
+                parse_args $*;;
+            --renaming)
+                if test -n "$renaming"; then error 'renaming file already set'; fi
+                shift
+                if test $# -eq 0; then error 'renaming file missing'; fi
+                renaming=$1
+                shift
+                parse_args $*;;
             *.ml)
                 if test -z "$hollight_file"
                 then
@@ -76,11 +84,22 @@ parse_args() {
             *.v)
                 if test -z "$root_path"
                 then
-                    error 'the root_path must be given before Rocq files'
+                    error 'the root_path must be given before'
                 else
-                    rocq_files="$rocq_files $1"
-                    vo_files="$vo_files `basename $1`o"
+                    rocqfiles="$rocqfiles $1"
+                    base_rocqfiles="$base_rocqfiles `basename $1`"
                     requiring="$requiring $root_path.`basename $1 .v`"
+                    shift
+                    parse_args $*
+                fi;;
+            *.lean)
+                if test -z "$root_path"
+                then
+                    error 'the root_path must be given before'
+                else
+                    leanfiles="$leanfiles $1"
+                    base_leanfiles="$base_leanfiles `basename $1`"
+                    requiring="$requiring $root_path.`basename $1 .lean`"
                     shift
                     parse_args $*
                 fi;;
@@ -115,8 +134,8 @@ echo create ROOT_PATH ...
 echo $root_path > ROOT_PATH
 
 echo create lambdapi.pkg ...
-echo "package_name = $root_path" > lambdapi.pkg
-echo "root_path = $root_path" >> lambdapi.pkg
+echo package_name = $root_path > lambdapi.pkg
+echo root_path = $root_path >> lambdapi.pkg
 
 echo create _CoqProject ...
 echo "-R . $root_path ." > _CoqProject
@@ -129,26 +148,43 @@ then
 fi
 echo $mapping > MAPPING
 
+echo create RENAMING ...
+if test -z "$renaming"
+then
+    touch renaming.lp
+    renaming=renaming.lp
+fi
+echo $renaming > RENAMING
+
 echo create REQUIRING ...
 echo $requiring > REQUIRING
 
-echo create VOFILES ...
-echo $vo_files > VOFILES
+echo create ROCQFILES ...
+echo $base_rocqfiles > ROCQFILES
+
+echo create LEANFILES ...
+echo $base_leanfiles > LEANFILES
 
 if test -z "$mk_file"
 then
     echo create deps.mk ...
-    echo $vo_files: > deps.mk
+    rm -f deps.mk
+    touch deps.mk
+    set $base_rocqfiles
+    if test $# -gt 0
+    then
+        echo -n ${1}o >> deps.mk
+        shift
+        for f in $*
+        do
+            echo -n " ${f}o" >> deps.mk
+        done
+        echo : >> deps.mk
+    fi
 else
     echo ln -f -s $mk_file deps.mk
     ln -f -s $mk_file deps.mk
 fi
-
-for f in $rocq_files
-do
-    echo cp -f $f .
-    cp -f $f .
-done
 
 for f in theory_hol.dk theory_hol.lp
 do
@@ -167,3 +203,24 @@ do
     echo ln -f -s $HOLLIGHT_DIR/${hollight_file%.ml}.$ext
     ln -f -s $HOLLIGHT_DIR/${hollight_file%.ml}.$ext
 done
+
+for f in $rocqfiles
+do
+    echo cp -f $f .
+    cp -f $f .
+done
+
+if test -n "$leanfiles"
+then
+    if test ! -d .lake
+    then
+       echo lake init $root_path math
+       lake init $root_path math
+       rm -f $root_path.lean $root_path/Basic.lean
+    fi
+    for f in $leanfiles
+    do
+        echo cp -f $f $root_path
+        cp -f $f $root_path
+    done
+fi
