wip

diff --git a/resize-proof b/resize-proof
--- a/resize-proof
+++ b/resize-proof
@@ -19,31 +19,33 @@ esac
 max=$2
 
 parts=`find . -name "${b}_part_*.lp"`
-parts="$parts $b.lp"
+parts="$parts $1"
 n=`ls $parts | wc -l`
-if test $n -eq 0; then echo "error: $b.lp does not exist"; exit 1; fi
+if test $n -eq 0; then echo "error: $1 does not exist"; exit 1; fi
 n=`expr $n - 1`
 
-if test ! -f $b.lp; then echo "error: $b.lp does not exist"; exit 1; fi
+if test ! -f $1; then echo "error: $1 does not exist"; exit 1; fi
 h=${b}_header.lp
 echo "generate $h ..."
-awk '/^require /{print;next}{nextfile}' $b.lp > $h
+awk '/^require /{print;next}{nextfile}' $1 > $h
 sed -i -e "/^require open hol-light.${b}_part_/d" $h
 
 p=${b}_proofs.lp
 echo "generate $p ..."
 cat `ls -v $parts` > $p
 sed -i -e '/^require /d' -e 's/^private /opaque /' $p
-#rm -f $parts
+rm -f $parts
 
-echo "generate $b.lp.bak ..."
-cat $h $p > $b.lp.bak
+echo "generate $1.bak ..."
+cat $h $p > $1.bak
 
+ls x[0-9]* 2> /dev/null
+if test $? -eq 0; then error "there already exist x[0-9]* files"; fi
 echo "split $p ..."
 split --numeric-suffixes=1 -a5 -l$max $p
 rm -f $p
 
-n=`ls x* | wc -l`
+n=`ls x[0-9]* | wc -l`
 for p in `ls x[0-9]*`
 do
     k=`expr ${p#x} + 0` # remove leading zeros
@@ -57,4 +59,4 @@ done
 rm -f $h
 
 echo "warning: all theorems are exported"
-echo "do \"make $b.lp\" to optimize this"
+echo "do \"make $1\" to optimize this"
